// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSetting():Promise<main.Settings>;

export function SaveSetting(arg1:main.Settings):Promise<void>;
