// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLiveStatus(arg1:main.Platforms,arg2:string):Promise<boolean>;

export function GetSetting():Promise<main.Settings>;

export function SaveSetting(arg1:main.Settings):Promise<void>;

export function StartGoLive():Promise<void>;
