// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSetting() {
  return window['go']['main']['App']['GetSetting']();
}

export function SaveSetting(arg1) {
  return window['go']['main']['App']['SaveSetting'](arg1);
}
