// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLiveStatus(arg1, arg2) {
  return window['go']['main']['App']['GetLiveStatus'](arg1, arg2);
}

export function GetSetting() {
  return window['go']['main']['App']['GetSetting']();
}

export function SaveSetting(arg1) {
  return window['go']['main']['App']['SaveSetting'](arg1);
}

export function StartGoLive() {
  return window['go']['main']['App']['StartGoLive']();
}
